version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/laravel/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    depends_on:
      - app
    networks:
      - persistent-stack_common

  app:
    build:
      context: ./docker
      dockerfile: LARAVEL.Dockerfile
    environment:
      - UID_GID=1000:1000
    ports:
      - '5173:5173'
    user: '${UID_GID}'
    volumes:
      - ./app:/app
    networks:
      - persistent-stack_common

networks:
  persistent-stack_common:
    external: true
